/**
 * Stable issue code identifiers for all validator checks.
 * Used as compile-time documentation and to prevent typos in check functions.
 *
 * Grouped by check category. Each code appears in exactly one check file.
 */
export const ISSUE_CODES = {
  // ----- parse-failure -----
  PARSE_FAILURE: 'PARSE_FAILURE',

  // ----- file-presence -----
  MISSING_REQUIRED_FILE: 'MISSING_REQUIRED_FILE',
  MISSING_FONT: 'MISSING_FONT',
  WRONG_AVATAR_COUNT: 'WRONG_AVATAR_COUNT',
  WRONG_AVATARICON_COUNT: 'WRONG_AVATARICON_COUNT',

  // ----- duplicates -----
  DUPLICATE_TILE_KEY: 'DUPLICATE_TILE_KEY',
  DUPLICATE_WORD_KEY: 'DUPLICATE_WORD_KEY',
  DUPLICATE_SYLLABLE_KEY: 'DUPLICATE_SYLLABLE_KEY',
  DUPLICATE_COLOR_INDEX: 'DUPLICATE_COLOR_INDEX',
  DUPLICATE_GAME_DOOR: 'DUPLICATE_GAME_DOOR',
  TILE_SELF_DUPLICATE_DISTRACTOR: 'TILE_SELF_DUPLICATE_DISTRACTOR',

  // ----- color-reference -----
  INVALID_KEYBOARD_COLOR_INDEX: 'INVALID_KEYBOARD_COLOR_INDEX',
  INVALID_TILE_COLOR_INDEX: 'INVALID_TILE_COLOR_INDEX',
  INVALID_GAME_COLOR_INDEX: 'INVALID_GAME_COLOR_INDEX',

  // ----- langinfo-required -----
  MISSING_LANGINFO_LABEL: 'MISSING_LANGINFO_LABEL',
  INVALID_SCRIPT_DIRECTION: 'INVALID_SCRIPT_DIRECTION',
  INVALID_SCRIPT_TYPE: 'INVALID_SCRIPT_TYPE',
  GAME_NAME_TOO_LONG_FOR_PLAY_STORE: 'GAME_NAME_TOO_LONG_FOR_PLAY_STORE',
  INVALID_ETHNOLOGUE_CODE: 'INVALID_ETHNOLOGUE_CODE',

  // ----- settings-types -----
  INVALID_BOOLEAN_SETTING: 'INVALID_BOOLEAN_SETTING',
  INVALID_INT_SETTING: 'INVALID_INT_SETTING',
  RATIO_OUT_OF_RANGE: 'RATIO_OUT_OF_RANGE',
  UNKNOWN_SETTING_KEY: 'UNKNOWN_SETTING_KEY',
  STAGE_CORRESPONDENCE_RATIO_IS_ONE: 'STAGE_CORRESPONDENCE_RATIO_IS_ONE',

  // ----- keyboard-coherence -----
  INVALID_KEYBOARD_COLOR: 'INVALID_KEYBOARD_COLOR',
  WORD_CHAR_NOT_IN_KEYBOARD: 'WORD_CHAR_NOT_IN_KEYBOARD',
  KEY_UNDERUSED: 'KEY_UNDERUSED',

  // ----- wordlist-characters -----
  INVALID_WORDLIST_LWC_CHARS: 'INVALID_WORDLIST_LWC_CHARS',
  MANY_WORDS_HAVE_SPACES: 'MANY_WORDS_HAVE_SPACES',
  FEW_WORDS_HAVE_SPACES: 'FEW_WORDS_HAVE_SPACES',
  EMPTY_LOP_VALUE: 'EMPTY_LOP_VALUE',

  // ----- tile-structure -----
  INVALID_TILE_TYPE: 'INVALID_TILE_TYPE',
  INVALID_DISTRACTOR: 'INVALID_DISTRACTOR',
  INCONSISTENT_UPPERCASE: 'INCONSISTENT_UPPERCASE',
  FULL_UPPERCASE_WARNING: 'FULL_UPPERCASE_WARNING',
  LOWERCASE_PLACEHOLDER: 'LOWERCASE_PLACEHOLDER',

  // ----- game-structure -----
  UNKNOWN_GAME_COUNTRY: 'UNKNOWN_GAME_COUNTRY',
  INVALID_CHALLENGE_LEVEL: 'INVALID_CHALLENGE_LEVEL',
  NON_SEQUENTIAL_GAME_DOORS: 'NON_SEQUENTIAL_GAME_DOORS',
  MISSING_INSTRUCTION_AUDIO: 'MISSING_INSTRUCTION_AUDIO',
  INVALID_AUDIO_DURATION: 'INVALID_AUDIO_DURATION',
  INSUFFICIENT_THREE_OR_FOUR_TILE_WORDS: 'INSUFFICIENT_THREE_OR_FOUR_TILE_WORDS',
  WORDLIST_TOO_SHORT_FOR_ITALY: 'WORDLIST_TOO_SHORT_FOR_ITALY',
  BRAZIL7_WITHOUT_TONAL_TILES: 'BRAZIL7_WITHOUT_TONAL_TILES',
  TONAL_TILES_WITHOUT_BRAZIL7: 'TONAL_TILES_WITHOUT_BRAZIL7',
  SUDAN_TILES_WITHOUT_TILE_AUDIO: 'SUDAN_TILES_WITHOUT_TILE_AUDIO',
  TILE_AUDIO_WITHOUT_SUDAN_TILES: 'TILE_AUDIO_WITHOUT_SUDAN_TILES',
  COLOMBIA_CL4_SYLLABLE: 'COLOMBIA_CL4_SYLLABLE',

  // ----- audio-reference -----
  MISSING_TILE_AUDIO: 'MISSING_TILE_AUDIO',
  MISSING_WORD_AUDIO: 'MISSING_WORD_AUDIO',
  MISSING_SYLLABLE_AUDIO: 'MISSING_SYLLABLE_AUDIO',
  MISSING_GAME_INSTRUCTION_AUDIO: 'MISSING_GAME_INSTRUCTION_AUDIO',
  ORPHAN_AUDIO_FILE: 'ORPHAN_AUDIO_FILE',
  ZERO_BYTE_AUDIO_FILE: 'ZERO_BYTE_AUDIO_FILE',
  OVERSIZE_AUDIO_FILE: 'OVERSIZE_AUDIO_FILE',
  AUDIO_TYPO_SUGGESTION: 'AUDIO_TYPO_SUGGESTION',

  // ----- image-reference -----
  MISSING_WORD_IMAGE: 'MISSING_WORD_IMAGE',
  ORPHAN_IMAGE_FILE: 'ORPHAN_IMAGE_FILE',
  IMAGE_TYPO_SUGGESTION: 'IMAGE_TYPO_SUGGESTION',

  // ----- tile-word-cross-ref -----
  WORD_CANNOT_PARSE_INTO_TILES: 'WORD_CANNOT_PARSE_INTO_TILES',
  WORD_TOO_LONG_FOR_GAMES: 'WORD_TOO_LONG_FOR_GAMES',
  WORD_LONGER_THAN_IDEAL: 'WORD_LONGER_THAN_IDEAL',
  TILE_UNDERUSED: 'TILE_UNDERUSED',

  // ----- stage-coherence -----
  STAGE_WORD_COUNT: 'STAGE_WORD_COUNT',
  EMPTY_STAGE: 'EMPTY_STAGE',
  INVALID_TILE_STAGE: 'INVALID_TILE_STAGE',

  // ----- syllables-coherence -----
  SYLLABLES_SKIPPED: 'SYLLABLES_SKIPPED',
  UNKNOWN_SYLLABLE_REFERENCE: 'UNKNOWN_SYLLABLE_REFERENCE',
  SYLLABLE_NOT_USED_IN_WORDLIST: 'SYLLABLE_NOT_USED_IN_WORDLIST',
  SYLLABLE_SELF_DUPLICATE_DISTRACTOR: 'SYLLABLE_SELF_DUPLICATE_DISTRACTOR',
  SYLLABLE_INVALID_DISTRACTOR: 'SYLLABLE_INVALID_DISTRACTOR',
  SYLLABLE_WORDS_WITHOUT_SYLLABLE_TAB: 'SYLLABLE_WORDS_WITHOUT_SYLLABLE_TAB',
  SYLLABLE_TAB_WITHOUT_SYLLABLE_WORDS: 'SYLLABLE_TAB_WITHOUT_SYLLABLE_WORDS',
} as const;

export type IssueCode = (typeof ISSUE_CODES)[keyof typeof ISSUE_CODES];
