name: ci-per-language-builds
artifacts:
  proposal:
    status: done
    path: proposal.md
  design:
    status: done
    path: design.md
    dependencies: [proposal]
  tasks:
    status: done
    path: tasks.md
    dependencies: [design]
  spec:
    status: done
    path: specs/ci-per-language-builds/spec.md
    dependencies: [design]
apply:
  requires: [tasks, spec]
  status: pending
