/**
 * Phase 1 spike for game-india-deva. Loads our extracted Devanagari stroke
 * JSON for `अ` and feeds it through @jamsch/react-native-hanzi-writer's
 * `loader` prop to verify the lib is script-agnostic. Lazy-imports the lib
 * inside useEffect (web SSR rule — see openspec/changes/game-taiwan/STATUS.md).
 */
import { useEffect, useState } from 'react';
import { Button, Text, View } from 'react-native';
import { GestureHandlerRootView } from 'react-native-gesture-handler';

type HanziModule = typeof import('@jamsch/react-native-hanzi-writer');

// Inlined to avoid importing from tools/. Generated by:
//   bun tools/build-stroke-data-deva.ts
// Then read tools/data/devanagari-strokes/अ.json and paste here.
import devaA from '../../../tools/data/devanagari-strokes/अ.json';

export default function SpikeDeva(): React.JSX.Element {
  const [mod, setMod] = useState<HanziModule | null>(null);
  useEffect(() => {
    import('@jamsch/react-native-hanzi-writer').then(setMod);
  }, []);
  if (!mod) return <Text>Loading hanzi-writer…</Text>;
  return <SpikeInner mod={mod} />;
}

function SpikeInner({ mod }: { mod: HanziModule }) {
  const { HanziWriter, useHanziWriter } = mod;
  const writer = useHanziWriter({
    character: 'अ',
    loader: () => ({
      strokes: devaA.strokes as unknown as string[],
      medians: devaA.medians as unknown as number[][][],
    }),
  });
  const quizActive = writer.quiz.useStore((s) => s.active);

  return (
    <GestureHandlerRootView style={{ flex: 1, backgroundColor: '#fff' }}>
      <View style={{ flex: 1, padding: 24, gap: 16 }}>
        <Text style={{ fontSize: 18 }}>spike-deva: अ — {devaA.strokes.length} strokes</Text>
        <HanziWriter
          writer={writer}
          loading={<Text>Loading…</Text>}
          error={<Text>Error loading character.</Text>}
          style={{ alignSelf: 'center' }}
        >
          <HanziWriter.GridLines color="#ddd" />
          <HanziWriter.Svg>
            <HanziWriter.Outline color="#ccc" />
            <HanziWriter.Character color="#1565c0" radicalColor="#2e7d32" />
            <HanziWriter.QuizStrokes />
            <HanziWriter.QuizMistakeHighlighter color="#e53935" strokeDuration={400} />
          </HanziWriter.Svg>
        </HanziWriter>
        <Button
          onPress={
            quizActive
              ? writer.quiz.stop
              : () => writer.quiz.start({ leniency: 1.5, showHintAfterMisses: 3 })
          }
          title={quizActive ? 'Stop Quiz' : 'Start Quiz'}
        />
        <Button
          onPress={() => writer.animator.animateCharacter({ delayBetweenStrokes: 600, strokeDuration: 600 })}
          title="Animate"
        />
      </View>
    </GestureHandlerRootView>
  );
}
