name: game-myanmar
artifacts:
  proposal:
    status: done
    path: proposal.md
  design:
    status: done
    path: design.md
    dependencies: [proposal]
  tasks:
    status: done
    path: tasks.md
    dependencies: [design]
  specs/game-myanmar:
    status: done
    path: specs/game-myanmar/spec.md
    dependencies: [design]
apply:
  requires: [tasks, specs/game-myanmar]
  status: complete
