name: game-ecuador
artifacts:
  proposal:
    status: done
    path: proposal.md
  design:
    status: done
    path: design.md
    dependencies: [proposal]
  tasks:
    status: done
    path: tasks.md
    dependencies: [design]
  specs/ecuador:
    status: done
    path: specs/ecuador/spec.md
    dependencies: [design]
apply:
  requires: [tasks, specs/ecuador]
  status: pending
