name: game-japan
artifacts:
  proposal:
    status: done
    path: proposal.md
  design:
    status: done
    path: design.md
    dependencies: [proposal]
  tasks:
    status: done
    path: tasks.md
    dependencies: [design]
  specs/japan:
    status: done
    path: specs/japan/spec.md
    dependencies: [design]
apply:
  requires: [tasks, specs/japan]
  status: pending
