name: game-thailand
artifacts:
  proposal:
    status: done
    path: proposal.md
  design:
    status: done
    path: design.md
    dependencies: [proposal]
  tasks:
    status: done
    path: tasks.md
    dependencies: [design]
  specs/thailand:
    status: done
    path: specs/thailand/spec.md
    dependencies: [design]
apply:
  requires: [tasks, specs/thailand]
  status: done
