name: app-store-metadata
artifacts:
  proposal:
    status: done
    path: proposal.md
  design:
    status: done
    path: design.md
    dependencies: [proposal]
  tasks:
    status: done
    path: tasks.md
    dependencies: [design]
  spec:
    status: done
    path: specs/app-store-metadata/spec.md
    dependencies: [design]
apply:
  requires: [tasks, spec]
  status: pending
