name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - run: npm ci --legacy-peer-deps

      - uses: nrwl/nx-set-shas@v4

      # Run lint and test only on affected projects
      - run: npx nx affected -t lint test --skip-nx-cache
        env:
          NX_NO_CLOUD: true
